### ISSUE TITLE
Runaway apostrophe in commit subject breaks hashing

### ISSUE THREAD

**Issue by davidsneighbour** [sourcerer-io/sourcerer-app#241]
I have an accidental apostrophe in one of the commits in my locally hashed repository:

```
[ 39.76%] * 5e90d06 changes'
[e] Error while hashing: GC overhead limit exceeded
The repositories have been hashed.
```
On initial scan sourcerer froze and I had to kill it after several minutes. 
On re-scanning sourcerer parses until that error, then freezes and stops processing and skips the repo.

I changed the label (`changes'` is the full label, nothing following behind) to `changes` and committed the changes, removed the repository from sourcerer, added it, but it still identifies the old label.

On removing repositories all data about it should be deleted from sourcerers cache and/or online database. Also special characters probably should be parsed out or be encoded somehow so the hashing does not fail.

**Comment by sergey-surkov** [comment]
Hi Patrick,

It is possible that an apostrophe is just a coincidence. The error is caused by the app running out of memory. Could you try increasing max heap memory available to JVM? If you used our standard script to install the app, you can:

1. Open ~/.sourcerer/sourcerer in a text editor
2. Find 'java' command in the end of the file. The current version looks as:

```
if [ $VERSION = 9 ] ; then
  java --add-modules java.activation --add-opens java.base/java.nio=ALL-UNNAMED -jar /Users/sergey/.sourcerer/sourcerer.jar "$@"
else
  java -jar /Users/sergey/.sourcerer/sourcerer.jar "$@"
fi
```
3. Add an option ```-Xms512m``` to the java commands

We will separately look into the apostrophe issue. Also, if by any chance you can provide us your repository for testing, we would appreciate it. If not, we'll try to reproduce based on your description.
