### ISSUE TITLE
Repos not detected for user

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#248]
The following user contacted me about several of his repos not being detected. 

user:
https://sourcerer.io/benwiley4000

an example repo he pointed out is:
https://github.com/sk8border/sk8border

**Comment by aoancea** [comment]
I'm having the same issue. This repo is not being tracked along with several other 20 https://github.com/aoancea/git-history

**Comment by sergey-surkov** [comment]
@anatolykislov could you check why we don't see https://github.com/aoancea/git-history ?

**Comment by anatolykislov** [comment]
Hi, benwiley4000!
sk8border repo is not presented in the profile because we are not supporting Pico-8, so we don't have any statistics from this repo. Should we add support of it?

**Comment by anatolykislov** [comment]
Hi, @aoancea !
We are not showing commits with a lot of vendor code to not affect profile statistics by it. For now we simply hide commits made in the same week if total LOCs count is more than 20000. Soon we will release configurable vendor filtering mechanism that will work almost like gitignore. With new filtering, it will become possible to show your repos.

**Comment by benwiley4000** [comment]
@anatolykislov I gave two repos and the other was JavaScript. Please use that instead (https://github/benwiley4000/react-responsive-audio-player).

**Comment by aoancea** [comment]
@anatolykislov so I'm guessing that;s the case for all the other repos?

and just one more thing, what vendor code are we talking about here since https://github.com/aoancea/git-history it's purely written by me in a readme.md with some asset files, or is readme.md considered vendor code as well?

**Comment by anatolykislov** [comment]
@benwiley4000 What do you mean by using of react-responsive-audio-player repository? This one seems to be detected correctly. Is something wrong with it?

**Comment by anatolykislov** [comment]
@aoancea that's the case for almost all repos, couple other repos are just too big (+300 MB) and can be processed by the app.
We are using brute filtering for now while we working on a customizable filtering. For example, git-history repo contains [the commit](https://github.com/aoancea/git-history/commit/f4f8cffa5712f329abe9758ae5db0b00828f2339) with big diff (+20000) it will be filtered just because of diff size. All other commits made in the same week will be filtered too because we aggregating commits with one week interval. Sorry about that issue, working on a fix.

**Comment by aoancea** [comment]
@anatolykislov fair enough :)
