### ISSUE TITLE
Processing FAILED for no reason

### ISSUE THREAD

**Issue by xorz57** [sourcerer-io/sourcerer-app#261]
![image](https://user-images.githubusercontent.com/1548352/38705722-2b5d90e2-3eb3-11e8-8bb1-591eea6acf96.png)

![image](https://user-images.githubusercontent.com/1548352/38705594-b84019e0-3eb2-11e8-8b48-0b05bfaf35b3.png)

**Comment by anatolykislov** [comment]
Hi, @xorz57!

Thank you for reporting an issue! Working on a permanent fix now.
Made quick fix for your account, you can try to sign up now again. It will be ok.

**Comment by anatolykislov** [comment]
Problem fixed completely. Rebuilding of profiles will occur without errors now.

**Comment by chandrakeshram** [comment]
I am also facing the errors of Processing FAILED everytime when I am trying to update my profile while adding my repositories . Kindly look into this and please do the prompt actions . Please fix this problem so that I can add my repos in my sourcerer account and update my profile.
![Capture](https://user-images.githubusercontent.com/79987328/147879932-0c7be709-e298-41b7-ab47-b6cdb2fdd8c0.PNG)
