### ISSUE TITLE
Emails sent to all followers without my permission

### ISSUE THREAD

**Issue by icyphox** [sourcerer-io/sourcerer-app#381]
Why was an unsolicited email sent to all my GitHub followers, without prior permission from me? This isn't quite right.

**Comment by icyphox** [comment]
Ah yikes. I think I might've missed a checkbox.

**Comment by sergey48k** [comment]
Hi @icyphox ,

Sorry for the inconvenience this has caused. We are making this checkbox more visible to reduce accidental notifications. Should be in prod by Monday. On our end, the reasoning was:

* Followers choose to follow precisely because they are interested in coding-related updates from people they follow.
* We understand that indiscriminate emails are not likely to be welcome, so we are making an effort to be more precise in targeting select followers who may be the most interested in seeing the coding activity and work you do. 
* We provide standard unsubscribe function so that it’s easy for people to never receive those updates again.

Again, sorry for the inconvenience, and we are hoping that in the next few days we will align this feature with what users are interested in.  Also, If you have any particular suggestions, please let me know.  This is definitely a work progress.

**Comment by icyphox** [comment]
It's all good. Glad to see this being addressed.

**Comment by stephentuso** [comment]
I thought I unchecked the box but the emails were still sent... but who knows, maybe I refreshed the page or something. Definitely shouldn't be a default.

**Comment by silverbucket** [comment]
The checkbox should not be enabled by default if it's that easy to miss, I don't recall seeing a checkbox at all.

**Comment by icyphox** [comment]
I actually agree with @silverbucket, I never saw any checkbox to begin with.
