### ISSUE TITLE
Support for Svelte

### ISSUE THREAD

**Issue by edgarberlinck** [sourcerer-io/sourcerer-app#523]
Hi. Have you guys any plan to support Svelte (https://svelte.dev/)?

**Comment by sergey48k** [comment]
We don't but if it's just detecting extension, it should not be too hard. @yaronskaya , what do you think?

**Comment by edgarberlinck** [comment]
I`m trying to do, but I don`t understand some points of your code.

I did the same logic at JavascriptExtractor to detect .svelt files just like Vue files. I think it should work after I update the awesomeLibs files and create a js.svelte property.

My problem is: The tests are not passing. Can you guys take a look at may code? Maybe I`m close to do it. 

https://github.com/edgarberlinck/sourcerer-app/commit/8ec8c2b84c75821422893f9837d2550a24bedcbc

**Comment by yaronskaya** [comment]
Hi @edgarberlinck, 
first of all add the library to [sourcerer-io/awesome-libraries](https://github.com/sourcerer-io/awesome-libraries) so that it to be indexed to be shown in the profile. Also add a test like [this](https://github.com/sourcerer-io/sourcerer-app/blob/06252cd5a980d2f6097395ffb6cb57769c591033/src/test/kotlin/test/tests/hashers/CommitHasherTest.kt#L344).
Your code passes tests for me.

**Comment by edgarberlinck** [comment]
Nice. Thanks for your help @yaronskaya, that helps me alot!

My pull requests are ready, I think everything is ok. Glad to contribute to this amazing tool.
