### ISSUE TITLE
Doubling the repositories on refresh

### ISSUE THREAD

**Issue by ghost** [sourcerer-io/sourcerer-app#618]
while updating repositories from refresh 
the value on the total repositories are getting doubled 
for ex:
it shows ``` updating 3 out of 12 repositories```
and on clicking update repositories
it shows``` updating 6 out of 24 repositories```
and more the clicks the double the values are changing

**Comment by Zircoz** [comment]
Hey @Lalisfeed , it is happening because every refresh click makes a stack of repos to be "refreshed" or reevaluated, as you click multiple times, it keeps on adding on to that stack. I am not sure if this project is still maintained, but a possible fix would be to disable that button while repos are still getting evaluated.

**Comment by ghost** [comment]
That's a good idea I guess
